# Generated by Django 6.0.3 on 2026-03-08 03:21

from django.db import migrations


def create_categories(apps, schema_editor):
    Category = apps.get_model('core', 'Category')
    
    categories = [
        {
            'name': 'Random Thoughts',
            'color': '#EF9C66'
        },
        {
            'name': 'School',
            'color': '#FCDC94'
        },
        {
            'name': 'Personal',
            'color': '#78ABA8'
        }
    ]
    
    for category_data in categories:
        Category.objects.get_or_create(
            name=category_data['name'],
            defaults={
                'color': category_data['color']
            }
        )


def reverse_create_categories(apps, schema_editor):
    Category = apps.get_model('core', 'Category')
    Category.objects.filter(name__in=['Random Thoughts', 'School', 'Personal']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_categories, reverse_create_categories),
    ]
